JobBoard.Web/Areas/GlobalAdmin/Controllers/ManageUsersController.cs
using JobPortal.BAL.Abstraction;
using JobPortal.BAL.Common;
using Microsoft.VisualBasic.FileIO;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.Areas.GlobalAdmin.Controllers
{
    [Web.UserLogin]
    [Web.RoleAuthorization]
    public class ManageUsersController : Controller
    {
        private readonly BAL.Abstraction.IBALUsers _bALUsers;
        private readonly BAL.Abstraction.IBALTrainings _bALTraining;
        private readonly BAL.Abstraction.IBALRegions _bALRegions;

        public ManageUsersController(BAL.Abstraction.IBALUsers bALUsers, IBALTrainings ibALTraining, IBALRegions IBALRegions)
        {
            _bALUsers = bALUsers;
            _bALTraining = ibALTraining;
            _bALRegions = IBALRegions;
        }

        // GET: GlobalAdmin/ManageUsers
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult GetAllUsersByRegionID()
        {
            if (Session["RegionId"] != null)
            {
                int regionId = Convert.ToInt32(Session["RegionId"]);
                var academyTeams = _bALUsers.GetALLUsersWithALLDataByRegionId(regionId);
                var gridModel = new DataSourceResult { Data = academyTeams, Total = academyTeams.Count };
                var jsonResult = Json(gridModel, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            else
            {
                return null;
            }
        }
        public JsonResult GetAllUsers()
        {
            var academyTeams = _bALUsers.GetAllUsersBelowRoleId(2);
            var gridModel = new DataSourceResult { Data = academyTeams, Total = academyTeams.Count };
            var jsonResult = Json(gridModel, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpPost]
        public JsonResult InsertUpdateUser(Core.Entity.UsersEntity model)
        {

            string multipleTraining = string.Empty;
            foreach (var item in model.multipleTrainings)
            {
                multipleTraining += item + ",";
            }
            model.MultipleTrainingAssignedCommaSeperated = multipleTraining;

            string multipleRoles = string.Empty;
            foreach (var item in model.multipleRoles)
            {
                multipleRoles += item + ",";
            }
            model.MultipleRolesAssignedCommaSeperated = multipleRoles;

            int regionId = _bALUsers.InsertUpdate(model);
            var jsonResult = Json(regionId, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult GetUserById(int Id)
        {
            var userDetails = _bALUsers.GetUserById(Id);

            var jsonResult = Json(userDetails, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult DeleteUser(int userid)
        {
            int result = _bALUsers.DeleteUser(userid);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        //[HttpPost]
        //public ActionResult UploadExcel(HttpPostedFileBase FileUpload)
        //{
        //    List<string> data = new List<string>();
        //    if (FileUpload != null)
        //    {
        //        // tdata.ExecuteCommand("truncate table OtherCompanyAssets");  
        //        if (FileUpload.ContentType == "application/vnd.ms-excel" || FileUpload.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        //        {


        //            string filename = FileUpload.FileName;
        //            if (!Directory.Exists(Server.MapPath("~/Doc/")))
        //            {
        //                // Try to create the directory.
        //                DirectoryInfo di = Directory.CreateDirectory(Server.MapPath("~/Doc/"));
        //            }
        //            string targetpath = Server.MapPath("~/Doc/");
        //            FileUpload.SaveAs(targetpath + filename);
        //            string pathToExcelFile = targetpath + filename;
        //            var connectionString = "";
        //            if (filename.EndsWith(".xls"))
        //            {
        //                connectionString = string.Format("Provider=Microsoft.Jet.OLEDB.4.0; data source={0}; Extended Properties=Excel 8.0;", pathToExcelFile);
        //            }
        //            else if (filename.EndsWith(".xlsx"))
        //            {
        //                connectionString = string.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties=\"Excel 12.0 Xml;HDR=YES;IMEX=1\";", pathToExcelFile);
        //            }

        //            var adapter = new OleDbDataAdapter("SELECT * FROM [Sheet1$]", connectionString);
        //            var ds = new DataSet();

        //            adapter.Fill(ds, "ExcelTable");

        //            DataTable dtable = ds.Tables["ExcelTable"];

        //            //  string sheetName = "Sheet1";

        //            //var excelFile = new ExcelQueryFactory(pathToExcelFile);
        //            //var artistAlbums = from a in excelFile.Worksheet<JobPortal.Core.Entity.JobEntity>(sheetName) select a;

        //            foreach (DataRow dr in dtable.Rows)
        //            {
        //                JobPortal.Core.Entity.UsersEntity userEntity = new Core.Entity.UsersEntity();

        //                string region = Convert.ToString(dr["Region Name"]);
        //                if (!string.IsNullOrEmpty(region))
        //                {
        //                    var regiondetail = _bALRegions.GetRegionByName(region);
        //                    if (regiondetail != null)
        //                    {
        //                        userEntity.RegionId = regiondetail.Id;
        //                    }
        //                }

        //                string training = Convert.ToString(dr["TrainingName"]);
        //                string multipletrainings = string.Empty;
        //                foreach (string item in training.Split(','))
        //                {
        //                    if (!string.IsNullOrEmpty(item))
        //                    {
        //                        var trainingdetail = _bALTraining.GetTrainingsByName(item);
        //                        if (trainingdetail != null)
        //                        {
        //                            multipletrainings += trainingdetail.ID + ",";
        //                        }
        //                    }
        //                }




        //                userEntity.MultipleTrainingAssignedCommaSeperated = multipletrainings.TrimEnd(',');
        //                userEntity.FirstName = dr["FirstName"].ToString();
        //                userEntity.lastName = dr["lastName"].ToString();

        //                userEntity.EmailAddress = dr["EmailAddress"].ToString();
        //                userEntity.PhoneNumber = dr["PhoneNumber"].ToString();
        //                userEntity.userName = dr["userName"].ToString();
        //                userEntity.UserPassword = dr["UserPassword"].ToString();
        //                userEntity.userPosition = dr["userPosition"].ToString();

        //                userEntity.MultipleRolesAssignedCommaSeperated = "5";

        //                _bALUsers.InsertUpdate(userEntity);
        //            }
        //            //deleting excel file from folder  
        //            if ((System.IO.File.Exists(pathToExcelFile)))
        //            {
        //                System.IO.File.Delete(pathToExcelFile);
        //            }
        //            return RedirectToAction("index");
        //        }
        //        else
        //        {
        //            //alert message for invalid file format  
        //            data.Add("<ul>");
        //            data.Add("<li>Only Excel file format is allowed</li>");
        //            data.Add("</ul>");
        //            data.ToArray();
        //            return Json(data, JsonRequestBehavior.AllowGet);
        //        }
        //    }
        //    else
        //    {
        //        data.Add("<ul>");
        //        if (FileUpload == null) data.Add("<li>Please choose Excel file</li>");
        //        data.Add("</ul>");
        //        data.ToArray();
        //        return Json(data, JsonRequestBehavior.AllowGet);
        //    }

        //}

        [HttpPost]
        public ActionResult UploadExcel(HttpPostedFileBase FileUpload)
        {
            List<string> data = new List<string>();
            if (FileUpload != null)
            {
                // tdata.ExecuteCommand("truncate table OtherCompanyAssets");  
                //if (FileUpload.ContentType == "application/vnd.ms-excel" || FileUpload.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                //{


                string filename = FileUpload.FileName;
                if (!Directory.Exists(Server.MapPath("~/Doc/")))
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(Server.MapPath("~/Doc/"));
                }
                string targetpath = Server.MapPath("~/Doc/");
                FileUpload.SaveAs(targetpath + filename);
                string pathToExcelFile = targetpath + filename;
                // var connectionString = "";
                //if (filename.EndsWith(".xls"))
                //{

JobBoard.Web/Areas/SuperAdmin/Views/ManageUsers/Index.cshtml
@{
    /**/

    Layout = "~/Areas/superadmin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";

}

<div class="JobPortal-aboutUsPage darkbg">
    <div class="container">
        <h2>Manage Users</h2>
        <div class="JobPortal-aboutUsPage">
            <input type="button" name="btnAddNew" id="btnAddNew" value="Add New User" />
            @using (Html.BeginForm("UploadExcel", "ManageUsers", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="control-label col-md-2">Excel:</div>
                    <div class="col-md-10">
                        <input type="file" id="FileUpload" name="FileUpload" class="" />
                    </div>
                </div>
                <span id="lblError" style="color: red;"></span>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Upload" id="btnSubmit" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            }
            <div class="clearfix"></div>
            <div>
                <div id="dvToAcademyTeams"></div>
            </div>
            <div class="clearfix"></div>
            <div id="myModal" class="AddPoll">
                <div class="modal-content1">
                    <div class="modal-header1">
                        <h4 class="modal-title" id="myModalLabel"><span id="spCaption"></span></h4>
                    </div>
                    <div class="modal-body pollPopupContent">
                        <div class="PollRow">
                            <input type="hidden" id="hdnuserId" />
                        </div>
                        <div class="PollRow">
                            <div class="PollLeft">Region:</div>
                            <div class="PollRight">
                                <select id="drpRegion">
                                    <option value="0">Select Region</option>
                                </select>
                                <span id="spdrpRegion" style="color:red;display:none">Select Region</span>
                            </div>
                        </div>
                        <div class="PollRow">

                            <div class="PollLeft">User Name:</div>
                            <div class="PollRight">
                                <input id="txtuser" type="text" />
                                <span id="sptxtuser" style="color:red;display:none">Enter User Name</span>
                            </div>
                        </div>

                        <div class="PollRow">
                            <div class="PollLeft">First Name</div>
                            <div class="PollRight">
                                <input id="txtfirst" type="text" />
                                <span id="sptxtfirst" style="color:red;display:none">Enter First Name</span>
                            </div>
                        </div>
                        <div class="PollRow">
                            <div class="PollLeft">Last Name</div>
                            <div class="PollRight">
                                <input id="txtlastName" type="text" />
                                <span id="sptxtlastName" style="color:red;display:none">Enter Last Name</span>
                            </div>
                        </div>

                        <div class="PollRow">
                            <div class="PollLeft">Email Address</div>
                            <div class="PollRight">
                                <input id="txtEmailAddress" type="text" />
                                <span id="sptxtEmailAddress" style="color:red;display:none">Enter Email address</span>
                            </div>
                        </div>


                        <div class="PollRow">
                            <div class="PollLeft">User Password</div>
                            <div class="PollRight">
                                <input id="txtuserpassword" type="text" />
                                <span id="sptxtuserpassword" style="color:red;display:none">Enter Password</span>
                            </div>
                        </div>

                        <div class="PollRow">
                            <div class="PollLeft">Phone Number</div>
                            <div class="PollRight">
                                <input id="txtPhonenumber" type="text" />
                                <span id="sptxtPhonenumber" style="color:red;display:none">Enter Phone Number</span>
                            </div>
                        </div>

                        <div class="PollRow">
                            <div class="PollLeft">IsActive</div>
                            <div class="PollRight"><input id="ChkIsActive" type="checkbox" /> </div>
                        </div>
                        <div class="PollRow">
                            <div class="PollLeft">Postion:</div>
                            <div class="PollRight">
                                <select id="drpuserPosition">
                                    <option value="0">Select user Position</option>
                                    <option value="General Foreman">General Foreman</option>
                                    <option value="Foreman">Foreman</option>
                                    <option value="Journeyman">Journeyman</option>
                                    <option value="Apprentice">Apprentice</option>
                                    <option value="New Hire 0-3 Months">New Hire 0-3 Months</option>
                                </select>
                                <span id="spdrpuserPosition" style="color:red;display:none">Select User Position</span>
                            </div>
                        </div>
                        <div class="PollRow">
                            <div class="PollLeft">Training:</div>
                            <div class="PollRight">
                                <div id="checkboxtraning" style="max-height:70px; overflow:scroll;">


                                </div>
                                <span id="spcheckboxtraning" style="color:red;display:none">Select trainings</span>

                            </div>

                            <div class="PollRow">
                                <div class="PollLeft">Roles:</div>
                                <div class="PollRight">
                                    <div id="checkboxrolls" style="max-height:70px; overflow:scroll;"></div>
                                    <span id="spcheckboxrolls" style="color:red;display:none">Select Roles</span>
                                </div>


                                <div class="PollRow">
                                    <div class="PollButton">
                                        <button type="button" onclick="UpdateAcademyTeamById();" id="btn_AddNewAcademy" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_ListRefrences")

<script src="~/Areas/SuperAdmin/Scripts/ManageUsers.js"></script>