JobBoard.Web/Areas/GlobalAdmin/Controllers/ManageJobsController.cs
using JobPortal.BAL.Abstraction;
using JobPortal.BAL.Common;
using Microsoft.VisualBasic.FileIO;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.Areas.GlobalAdmin.Controllers
{
    [Web.UserLogin]
    [Web.RoleAuthorization]
    public class ManageJobsController : Controller
    {
        // GET: GlobalAdmin/ManageJobs
        private readonly BAL.Abstraction.IBALJobs _balService;
        private readonly BAL.Abstraction.IBALRegions _bALRegions;

        private readonly BAL.Abstraction.IBALJobTimeMapping _iBALJobTimeMapping;
        private readonly BAL.Abstraction.IBALJobTimeEmpMapping _iBALJobTimeEmpMapping;
        private readonly BAL.Abstraction.IBALTrainings _bALTraining;

        public ManageJobsController(IBALRegions IBALRegions, BAL.Abstraction.IBALJobs balService, IBALJobTimeMapping iBALJobTimeMapping
            , IBALJobTimeEmpMapping iBALJobTimeEmpMapping, IBALTrainings ibALTraining)
        {
            _balService = balService;
            _bALRegions = IBALRegions;
            _iBALJobTimeMapping = iBALJobTimeMapping;
            _iBALJobTimeEmpMapping = iBALJobTimeEmpMapping;
            _bALTraining = ibALTraining;
        }


        // GET: SuperAdmin/ManageJobs
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllJobs()
        {

            if (Session["RegionId"] != null)
            {
                var academyTeams = _balService.GetAllJobsbyRegion(Convert.ToInt32(Session["RegionId"]));
                var gridModel = new DataSourceResult { Data = academyTeams, Total = academyTeams.Count };
                var jsonResult = Json(gridModel, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            else
            {
                var academyTeams = _balService.GetAllJobs();
                var gridModel = new DataSourceResult { Data = academyTeams, Total = academyTeams.Count };
                var jsonResult = Json(gridModel, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }


        }
        public JsonResult GetAllJobsWithTrainings()
        {
            if (Session["RegionId"] != null)
            {
                var academyTeams = _balService.GetJobsWithTrainingName(Convert.ToInt32(Session["RegionId"]));
                var gridModel = new DataSourceResult { Data = academyTeams, Total = academyTeams.Count };
                var jsonResult = Json(gridModel, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            else {
                return null;
            }
        }

        public ActionResult JobTimeMapping()
        {
            return View();
        }

        [HttpPost]
        public JsonResult JobTimeMapping(Core.Entity.JobTimeMappingEntity model)
        {
            var jsonResult = Json(_iBALJobTimeMapping.InsertJobTimeMapping(model), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public ActionResult JobTimeAndEmpMapping()
        {
            return View();
        }


        public JsonResult GetAllJobTimeMapping()
        {
            var jsonResult = Json(_iBALJobTimeMapping.GetAllJobTimeMapping(), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult GetAllJobTimeEmpMapping()
        {
            var jsonResult = Json(_iBALJobTimeEmpMapping.GetAllJobTimeEmpMapping(), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }


        [HttpPost]
        public JsonResult JobTimeAndEmpMapping(Core.Entity.JobTimeMappingEntity model)
        {
            var jsonResult = Json(_iBALJobTimeEmpMapping.InsertJobTimeEmpMapping(model), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpPost]
        public JsonResult InsertUpdateJobs(Core.Entity.JobEntity model)
        {
            string multipleTraining = string.Empty;

            if (model.multipleTrainings != null && model.multipleTrainings.Count() > 0)
            {
                foreach (var item in model.multipleTrainings)
                {
                    multipleTraining += item + ",";
                }
                model.MultipleTrainingsAssignedCommaSeperated = multipleTraining;
            }


            int Id = _balService.InsertUpdate(model);
            var jsonResult = Json(Id, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult DeleteJobTimeMapping(int Id)
        {
            var result = _iBALJobTimeMapping.DeleteJobTimeMapping(Id);
            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult DeleteJobTimeAndEmpMapping(int Id)
        {
            var result = _iBALJobTimeEmpMapping.DeleteJobTimeAndEmpMapping(Id);
            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult CheckIfMatchedAnyTraining(int Jobid, int Userid)
        {
            var result = _iBALJobTimeEmpMapping.CheckIfMatchedAnyTraining(Jobid, Userid);
            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult GetJobById(int jobId)
        {
            var result = _balService.GetJobById(jobId);
            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public JsonResult DeleteJob(int Id)
        {
            var result = _balService.DeleteJob(Id);
            var jsonResult = Json(result, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpPost]
        public ActionResult UploadExcel(HttpPostedFileBase FileUpload)
        {
            List<string> data = new List<string>();
            if (FileUpload != null)
            {
                // tdata.ExecuteCommand("truncate table OtherCompanyAssets");  

                string filename = FileUpload.FileName;
                if (!Directory.Exists(Server.MapPath("~/Doc/")))
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(Server.MapPath("~/Doc/"));
                }
                string targetpath = Server.MapPath("~/Doc/");
                FileUpload.SaveAs(targetpath + filename);
                string pathToExcelFile = targetpath + filename;

                //  string sheetName = "Sheet1";

                //var excelFile = new ExcelQueryFactory(pathToExcelFile);
                //var artistAlbums = from a in excelFile.Worksheet<JobPortal.Core.Entity.JobEntity>(sheetName) select a;

                DataTable dtable = GetDataTabletFromCSVFile(pathToExcelFile);

                foreach (DataRow dr in dtable.Rows)
                {
                    JobPortal.Core.Entity.JobEntity jobEntity = new Core.Entity.JobEntity();



                    string region = Convert.ToString(dr["Region Name"]);
                    if (!string.IsNullOrEmpty(region))
                    {
                        var regiondetail = _bALRegions.GetRegionByName(region);
                        if (regiondetail != null)
                        {
                            jobEntity.RegionId = regiondetail.Id;
                        }
                    }

                    string training = Convert.ToString(dr["TrainingName"]);
                    string multipletrainings = string.Empty;
                    foreach (string item in training.Split(','))
                    {
                        if (!string.IsNullOrEmpty(item))
                        {
                            var trainingdetail = _bALTraining.GetTrainingsByName(item);
                            if (trainingdetail != null)
                            {
                                multipletrainings += trainingdetail.ID + ",";
                            }
                        }
                    }




                    jobEntity.MultipleTrainingsAssignedCommaSeperated = multipletrainings.TrimEnd(',');
                    jobEntity.JobTitle = dr["JobTitle"].ToString();
                    jobEntity.JobDescription = dr["JobDescription"].ToString();
                    jobEntity.JobNumber = Convert.ToString(dr["JobNumber"]);

                    int Status = 0;
                    switch (Convert.ToString(dr["Status"]).ToLower())
                    {
                        case "open":
                            Status = 1;
                            break;
                        case "in progress":
                            Status = 2;
                            break;
                        case "completed":
                            Status = 3;
                            break;
                        case "close":
                            Status = 4;
                            break;
                    }

                    jobEntity.Status = Status;

                    _balService.InsertUpdate(jobEntity);
                }
                //deleting excel file from folder  

JobBoard.Web/Areas/RegionAdmin/Views/ManageJobs/Index.cshtml
@{

    //Layout = "~/Areas/RegionAdmin/Views/Shared/_Layout.cshtml";
    Layout = "~/Areas/RegionAdmin/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";
}


<div class="JobPortal-aboutUsPage darkbg">
    <div class="container">
        <h2>Manage Jobs</h2>
        <div class="JobPortal-aboutUsPage">
            <input type="button" name="btnAddNew" id="btnAddNew" value="Add New Job" />
            @using (Html.BeginForm("UploadExcel", "ManageJobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="control-label col-md-2">Excel:</div>
                    <div class="col-md-10">
                        <input type="file" id="FileUpload" name="FileUpload" class="" />
                    </div>
                </div>
                <span id="lblError" style="color: red;"></span>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Upload" id="btnSubmit" class="btn btn-primary" />
                    </div>
                </div>
            </div>
            }
            <div class="clearfix"></div>
            <div>
                <div id="dvToAcademyTeams"></div>
            </div>
            <div class="clearfix"></div>
            <div id="myModal" title="Insert/Update Job" class="AddPoll">
                <div class="modal-content1">
                    <div class="modal-header1">
                        <h4 class="modal-title" id="myModalLabel">Insert/Update Job</h4>
                    </div>
                    <div class="modal-body pollPopupContent">
                        <div class="PollRow">
                            <input type="hidden" id="hdnJobId" />
                        </div>
                        <div class="PollRow">
                            <div class="PollLeft">JobTitle:</div>
                            <div class="PollRight"><input id="txtJobTitle" type="text" /><span id="sptxtJobTitle" style="color:red;display:none">Enter Job Title</span> </div>
                        </div>
                        <div class="PollRow">
                            <div class="PollLeft">Job Number:</div>
                            <div class="PollRight"><input id="txtJobNumber" type="text" /><span id="sptxtJobNumber" style="color:red;display:none">Enter Job Number</span> </div>
                        </div>
                        <div class="PollRow">
                            <div class="PollLeft">JobDescription:</div>
                            <div class="PollRight"><input id="txtJobDescription" type="text" /><span id="sptxtJobDescription" style="color:red;display:none">Enter Description</span> </div>
                        </div>


                        <div class="PollRow">
                            <div class="PollLeft">Region:</div>
                            <div class="PollRight">
                                @*<input id="txtRegionId" type="text" />*@
                                <select id="drpRegion">
                                    <option value="0">Select Region</option>
                                </select>
                                <span id="spdrpRegion" style="color:red;display:none">Select Region</span>
                            </div>
                        </div>

                        <div class="PollRow">
                            <div class="PollLeft">Trainings:</div>
                            <div class="PollRight" id="dvtraining">
                                <div id="checkboxContainer" style="max-height:70px; overflow:scroll;"></div>
                                <span id="spchk_training" style="color:red;display:none">Select Training</span>
                            </div>
                        </div>


                        <div class="PollRow">
                            <div class="PollLeft">Status:</div>
                            <div class="PollRight">

                                <select id="drpStatus">
                                    <option value="0">Select Status</option>
                                    <option value="1">Open</option>
                                    <option value="2">In Progress</option>
                                    <option value="3">Completed</option>
                                    <option value="4">Close</option>
                                </select>
                                <span id="spdrpStatus" style="color:red;display:none">Select Status</span>
                                @*<input id="txtStatus" type="text" />*@




                            </div>
                        </div>


                        <div class="PollRow">
                            <div class="PollLeft">IsActive:</div>
                            <div class="PollRight"><input id="chkIsActive" checked="checked" type="checkbox" /> </div>
                        </div>


                        <div class="PollRow">
                            <div class="PollButton">
                                <button type="button" onclick="UpdateAcademyTeamById();" id="btn_AddNewAcademy" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("_ListRefrences")

<script src="~/Areas/RegionAdmin/Scripts/ManageJobs.js"></script>

JobBoard.Web/Areas/RegionAdmin/Views/ManageJobs/JobTimeAndEmpMapping.cshtml
@{
    ViewBag.Title = "JobTimeAndEmpMapping";
    Layout = "~/Areas/RegionAdmin/Views/Shared/_Layout.cshtml";
}

<h2>Job Time And Emp Mapping</h2>

<strong>Job Time Mapping</strong><br />
<div style="position:absolute; max-height: 150px; width:90.7%;
    overflow: scroll; border:2px solid black; " ondragover="allowDrop(event)" id="dvJobsTime"></div>

<br clear="all" />
<br clear="all" />
<br clear="all" />
<br clear="all" />
<br clear="all" />
<div style="height:60px"></div>
<strong style="margin:33px 0px 0px 0px;">Employees</strong><br />
<input type="text" id="search-criteria" onkeyup="searchEmps()" />
<div style="width:110%; float:left;max-height: 150px;margin:33px 0px 0px 0px; overflow:scroll; border:2px solid black;" ondragover="allowDrop(event)" id="dvEmps"></div>
<br clear="all" />
<br clear="all" />
<br clear="all" />

<strong>Time Job and Emp Mapping</strong><br />

<div style="float:left;max-height: 300px; overflow: scroll;width:100%">
    <strong> Time Job Mapping</strong><br />
    <table id="tbTimeJobEmpMapping" style="border:2px solid black; width:100%">
        <thead>
            <tr style="border:1px solid black">
                <td style="border:1px solid black;font-weight:bold;">Job</td>
                <td style="border:1px solid black;font-weight:bold;">Time</td>
                <td style="border:1px solid black;font-weight:bold;">Employee</td>
                <td style="border:1px solid black;font-weight:bold; text-align:center">Remove</td>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>



<script>
    function searchEmps() {
        $('.contact-name').hide();
        var txt = $('#search-criteria').val();
        $('.contact-name').each(function () {
            if ($(this).text().toUpperCase().indexOf(txt.toUpperCase()) != -1) {
                $(this).show();
            }
        });
    }
    function allowDrop(ev) {
        ev.preventDefault();
    }

    function Empdrag(ev) {
        ev.dataTransfer.setData("text", ev.currentTarget.innerText);
        ev.dataTransfer.setData("UserId", ev.currentTarget.id);
    }

    function Empdrop(ev) {
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text");
    }

    function JobTimedrop(ev) {
        ev.preventDefault();
        var data = ev.dataTransfer.getData("text");
        var UserId = ev.dataTransfer.getData("UserId").split('_')[1];
        var jobTimeMappingId = ev.currentTarget.id.split('_')[1];


        var model = { EmpId: parseInt(UserId), ID: jobTimeMappingId };

        var json = JSON.stringify(model);
        let resulsss = false;
        $.ajax({
            url: "/GlobalAdmin/ManageJobs/CheckIfMatchedAnyTraining?Jobid=" + jobTimeMappingId + "&Userid=" + UserId,
            type: 'get',
            async: false,
            success: function (result) {

                if (result == true) {
                    resulsss = true;
                }
                else {
                    resulsss = false;
                }
            },
            failure: function (result) {
                swal(result.responseText);
            },
            error: function (result) {
                swal(result.responseText);
            }
        });

        if (resulsss == true) {
            $.ajax({
                url: "/RegionAdmin/ManageJobs/JobTimeAndEmpMapping",
                type: 'POST',
                data: json,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (result) {
                    if (result > 0) {
                        if (result == 09090) {
                        } else {
                            var dvhtml = '<tr  style="border:1px solid black"><td style="border:1px solid black" id="div_' + result + '">' + ev.target.innerText.split('Starts at')[0] + '</span></td><td  style="border:1px solid black">' + ev.target.innerText.split('Starts at')[1] + '</td><td  style="border:1px solid black">' + data + '</td><td  style="border:1px solid black"><span  style="float: right;" onclick=deleteTimeJobMapping(' + result + ') id=sp_' + result + '><img src="/Content/Images/delete.png" /></span></td></tr>';
                            $("#tbTimeJobEmpMapping tbody").prepend(dvhtml);
                            swal('Job Assigned to the time');
                        }
                    }
                },
                failure: function (result) {
                    swal(result.responseText);
                },
                error: function (result) {
                    swal(result.responseText);
                }
            });
        } else {
            if (confirm("User does not have the specified Trainings, still you want to continue")) {
                $.ajax({
                    url: "/RegionAdmin/ManageJobs/JobTimeAndEmpMapping",
                    type: 'POST',
                    data: json,
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        if (result > 0) {
                            if (result == 09090) {
                            } else {
                                var dvhtml = '<tr  style="border:1px solid black"><td style="border:1px solid black" id="div_' + result + '">' + ev.target.innerText.split('Starts at')[0] + '</span></td><td  style="border:1px solid black">' + ev.target.innerText.split('Starts at')[1] + '</td><td  style="border:1px solid black">' + data + '</td><td  style="border:1px solid black"><span  style="float: right;" onclick=deleteTimeJobMapping(' + result + ') id=sp_' + result + '><img src="/Content/Images/delete.png" /></span></td></tr>';
                                $("#tbTimeJobEmpMapping tbody").prepend(dvhtml);
                                swal('Job Assigned to the time');
                            }
                        }
                        else {
                            alert("Some error occured. Please try again.");
                        }
                    },
                    failure: function (result) {
                        swal(result.responseText);
                    },
                    error: function (result) {
                        swal(result.responseText);
                    }
                });
            }
        }



    }

    function IfJobAndEmpHasSameTraings(jobId, empId) {

    }

    $(document).ready(function () {
        CreateJobTimeDiv();
        CreateEmpDiv();
        CreateJobTimeAndEmpMappingDiv();
    });

    function CreateJobTimeDiv() {
        $('[id$=dvJobsTime]').html('');

        var dvhtml = '';
        $.ajax({
            url: "/RegionAdmin/ManageJobs/GetAllJobTimeMapping",
            type: 'get',
            success: function (result) {

                if (result != false) {
                    $.each(result, function (data, value) {
                        dvhtml += '<div style="border:1px solid black; margin: 4px 12px 4px; float: left; width:200px" id="div_' + value.ID + '"  ondrop="JobTimedrop(event)" ><span id="div_' + value.ID + '">' + value.JobTitle + ' Starts at ' + value.Time + '</span></div>';
                    });
                    $('[id$=dvJobsTime]').html(dvhtml);
                }
            },
            failure: function (result) {
                swal(result.responseText);
            },
            error: function (result) {
                swal(result.responseText);
            }
        });
    }


    function CreateEmpDiv() {
        $('[id$=dvEmps]').html('');

        var dvhtml = '';
        $.ajax({
            url: "/RegionAdmin/ManageUsers/GetAllUsersByRegionID",
            type: 'get',
            success: function (result) {

                if (result != false) {
                    $.each(result.Data, function (data, value) {
                        if (value.userPosition == 'General Foreman') {
                            dvhtml += '<div class="contact-name" title="' + value.MultipleTrainingAssignedCommaSeperated +'"  style="border:1px solid black;background-color:green; color:white; margin: 4px 12px 4px; float: left; width:200px" id="div_' + value.UserId + '"  ondrop="Empdrop(event)" ondragover="allowDrop(event)"><span draggable="true" ondragstart="Empdrag(event)" id="div_' + value.UserId + '">' + value.FirstName + '' + value.lastName + '</span></div>';
                        } else if (value.userPosition == 'Foreman') {
                            dvhtml += '<div class="contact-name" title="' + value.MultipleTrainingAssignedCommaSeperated +'"  style="border:1px solid black;background-color:blue; color:white; margin: 4px 12px 4px; float: left; width:200px" id="div_' + value.UserId + '"  ondrop="Empdrop(event)" ondragover="allowDrop(event)"><span draggable="true" ondragstart="Empdrag(event)" id="div_' + value.UserId + '">' + value.FirstName + '' + value.lastName + '</span></div>';
                        } else if (value.userPosition == 'Journeyman') {
                            dvhtml += '<div class="contact-name" title="' + value.MultipleTrainingAssignedCommaSeperated +'"   style="border:1px solid black;background-color:red; color:white; margin: 4px 12px 4px; float: left; width:200px" id="div_' + value.UserId + '"  ondrop="Empdrop(event)" ondragover="allowDrop(event)"><span draggable="true" ondragstart="Empdrag(event)" id="div_' + value.UserId + '">' + value.FirstName + '' + value.lastName + '</span></div>';
                        } else if (value.userPosition == 'Apprentice') {
                            dvhtml += '<div class="contact-name" title="' + value.MultipleTrainingAssignedCommaSeperated+'"  style="border:1px solid black;background-color:yellow; color:black; margin: 4px 12px 4px; float: left; width:200px" id="div_' + value.UserId + '"  ondrop="Empdrop(event)" ondragover="allowDrop(event)"><span draggable="true" ondragstart="Empdrag(event)" id="div_' + value.UserId + '">' + value.FirstName + '' + value.lastName + '</span></div>';
                        } else if (value.userPosition == 'New Hire 0-3 Months') {
                            dvhtml += '<div class="contact-name" title="' + value.MultipleTrainingAssignedCommaSeperated +'"  style="border:1px solid black;background-color:white; margin: 4px 12px 4px; float: left; width:200px" id="div_' + value.UserId + '"  ondrop="Empdrop(event)" ondragover="allowDrop(event)"><span draggable="true" ondragstart="Empdrag(event)" id="div_' + value.UserId + '">' + value.FirstName + '' + value.lastName + '</span></div>';
                        }  });
                    $('[id$=dvEmps]').html(dvhtml);
                }
            },
            failure: function (result) {
                swal(result.responseText);
            },
            error: function (result) {
                swal(result.responseText);
            }
        });
    }


    function CreateJobTimeAndEmpMappingDiv() {

        $("#tbTimeJobEmpMapping tbody").html('');

        $.ajax({
            url: "/RegionAdmin/ManageJobs/GetAllJobTimeEmpMapping",
            type: 'get',
            success: function (result) {

                if (result != false) {
                    $.each(result, function (data, value) {
                        var dvhtml = '<tr  style="border:1px solid black"><td style="border:1px solid black" id="div_' + value.ID + '">' + value.JobTitle + '</span></td><td  style="border:1px solid black">' + value.Time + '</td><td  style="border:1px solid black">' + value.EmpName + '</td><td  style="border:1px solid black"><span  style="float: right;" onclick=deleteTimeJobMapping(' + value.ID + ') id=sp_' + value.ID + '><img src="/Content/Images/delete.png" /></span></td></tr>';
                        $("#tbTimeJobEmpMapping tbody").append(dvhtml);
                    });
                }
            },
            failure: function (result) {
                swal(result.responseText);
            },
            error: function (result) {
                swal(result.responseText);
            }
        });
    }

    function deleteTimeJobMapping(id) {
        $.ajax({
            url: "/RegionAdmin/ManageJobs/DeleteJobTimeAndEmpMapping?Id=" + id,
            type: 'get',
            success: function (result) {
                if (result) {
                    swal("Job,Time and Emp Mapping Deleted");
                    CreateJobTimeAndEmpMappingDiv();
                }
                else {
                    alert("Some error occured. Please try again.");
                }
            },
            failure: function (result) {
                swal(result.responseText);
            },
            error: function (result) {
                swal(result.responseText);
            }
        });
    }
</script>

JobBoard.Web/Areas/RegionAdmin/Views/ManageJobs/JobsAssignedToEmp.cshtml
@{
    /**/

    ViewBag.Title = "JobsAssignedToEmp";
}

<h2>Jobs Assigned To Employee</h2>

<div>
    <div id="dvToAcademyTeams"></div>
</div>
<div class="clearfix"></div>
@Html.Partial("_ListRefrences")
<script>
    BindJobsList();
    //Bind Academy Teams Grid
    function BindJobsList() {
        var url = "/RegionAdmin/ManageJobs/GetAllJobsAssigneToEmpByRegion";

        $("#dvToAcademyTeams").kendoGrid({
            toolbar: ["excel", "pdf"],
            dataSource: {
                autoBind: false,
                transport: {
                    read: url
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        fields: {
                            OrgRule: { type: "string" }
                        }
                    }
                },
                pageSize: 15,
                serverPaging: false,
            },
            pageable: {
                pageSize: 15,
                info: true,
                refresh: false
            },
            columnMenu: true,
            onetouch: true,
            sortable: true,
            scrollable: true,
            filterable: {
                extra: false
            }, excelExport: function (e) {
                e.workbook.fileName = "result.xlsx";
            }, pdf: {
                allPages: true
            },
            columns: [
                {
                    field: "JobTitle",
                    title: "JobTitle"
                },
                {
                    field: "EmpName",
                    title: "Emp Name"
                },
                {
                    field: "Time",
                    title: "Time"
                }
            ],
            pageable: {
                pageSizes: [15, 50, 75, 100]
            }
        });
    }
</script>